### ISSUE TITLE
grew count handling deep features

### ISSUE THREAD

**Issue by s-herrera** [grew-nlp/grew#19]
Hello,

I think the command grew count (and by extension grew_count in Python) is not handling well the feature "deep" when we query dependency relations as features. This works well in Grew-Match. Maybe i'm writing bad the patterns. 

As exemple, i use the corpus SUD_French-GSD@2.10, and the values of the relation "flat" and "mod".

flat [16], flat:foreing [4], flat:name [2], flat@foreing [978], flat@name [6991]

| pattern      | #  | ok? |
|--------------|----|-----|
| X-[flat]->Y  | 16 | Yes |
| X[1=flat]->Y |  22  |  No. It only counts those that don't have a "deep" feature  |
| X-[1=flat, 2=name]->Y | 2 |  Yes   |
| X-[1=flat, 2=*]->Y | 6 |  Yes   |
| X-[1=*, 2=name]->Y | 2 |  Yes   |
| X-[1=flat, deep=name]->Y | 0 |  No |
| X-[1=flat, deep=*]->Y | 0 |  No |

mod [61579], mod@relcl [3334], mod@x [1625]

| pattern      | #  | ok? |
|--------------|----|-----|
| X-[mod]->Y  | 61579 | Yes 
| X-[mod@relcl]->Y  | 3334 | Yes |
| X-[1=mod]->Y  | 61579 | No. It only counts those that don't have a "deep" feature |
| X-[1=mod, deep=relcl]->Y  | 0 | No |
| X-[1=mod, deep=*]->Y  | 0 | No |

**Comment by bguil** [comment]
Your problem is linked to a `config` problem. This should be improved but here is the current situation:

The mapping from the compact label feature `flat:name` and the feature structure one (`1=flat, 2=name`) is not independent from the kind of data we manipulate (i.e. SUD has `@` whereas UD has not).
In Grew, to deal with this you should give a `config` to say in which context you are. More on this [here](https://grew.fr/doc/graph/#edges).

For `grew count`, the config can be given in the JSON file. With the file `gsd.json`, the same GSD corpus in built once with the UD config (the default) and once with the SUD config.

```
{ "corpora": [
  { 
    "id": "GSD_config_ud",
    "directory": "SUD_French-GSD"
  },
  { 
    "id": "GSD_config_sud",
    "config": "sud",
    "directory": "SUD_French-GSD"
  }
  ]
}
```

With the pattern `pattern { X -[1=flat]->Y }` in the file `flat.pat`, we observe that:

```
grew compile -i gsd.json
grew count -i gsd.json -pattern flat.pat
```

outputs:

```
Corpus	# sentences	flat
GSD_config_ud	16341	22
GSD_config_sud	16341	7991
```

With the SUD config, this is the expected output, but with the UD config, label `flat@name` is interpreted as `1=flat@name` which does not match the pattern. 

With the Python library, the UD config is unfortunately hard-coded in the lib.
I will propose a new version of the lib with a function for changing the config ASAP. I let the issue open in the mean time.

**Comment by bguil** [comment]
Updates are available:
 * In ocaml: `opam update && opam upgrade grewpy` to install `grewpy` version 1.9.1
 * in python: `pip install grew --upgrade` to install the `grew` lib version 0.5.0
 
Then the following code:
```python
import grew
grew.init()
files = [
  "SUD_French-GSD/fr_gsd-sud-dev.conllu",
  "SUD_French-GSD/fr_gsd-sud-test.conllu",
  "SUD_French-GSD/fr_gsd-sud-train.conllu"
]

corpus = grew.corpus (files)
print ("with ud config: " + str(grew.corpus_count("pattern { X -[1=flat]->Y }", corpus)))

grew.set_config("sud")

corpus = grew.corpus (files)
print ("with sud config: " + str(grew.corpus_count("pattern { X -[1=flat]->Y }", corpus)))
```

produces:

```
with ud config: 22
with sud config: 7991
```

**Comment by s-herrera** [comment]
Amazing. I close the issue.
