### ISSUE TITLE
search seems to be down

### ISSUE THREAD

**Issue by LeonieWeissweiler** [grew-nlp/grew#45]
Hi,

the website seems to be down right now, I'm getting an error "Connection fail The search service is not available."

**Comment by bguil** [comment]
Thanks for reporting.
I've restarted the server. It should be Ok now.

**Comment by LeonieWeissweiler** [comment]
thanks so much for the quick response! It's still throwing the same error now, should I just wait a few more minutes?

**Comment by bguil** [comment]
The server seems to be overloaded. On which treebank are you working on?

**Comment by LeonieWeissweiler** [comment]
German HDT

**Comment by bguil** [comment]
This is the largest treebank in UD. It is quite difficult to manage it.
I re-open and I will try to improve it. Unfortunatly I do not have a solution in the meantime.

**Comment by bguil** [comment]
I have run a few requests on German-HDT, it works within a few seconds.
I think that you should really wait for the reply of a request before clicking again on "search" to avoid overloading.

**Comment by LeonieWeissweiler** [comment]
I think I may have a query that just results in a connection error?
I just ran my first request of the day and immediately got a connection fail again, after about 30s of waiting.

the query was:

pattern { 
F[form="Fall"|"Falle"];
D[form="den"];
X[lemma="Gesetzt"|"Für"|"gesetzt"|"für"];
D < F;
X < D;
Y1[form<>"dass"|"daß"];
Y2[form<>"dass"|"daß"];
}

I then tried running just the first line, which worked fine, and then I ran this one again, and it resulted in a connection fail again.

**Comment by LeonieWeissweiler** [comment]
I think I've taken the website down again, sorry :( I really only clicked on the "search" button once this time

**Comment by kirianguiller** [comment]
Hi Leonie, I don't know the exact reason of your connection error (that is caused by a timeout), but if you need to do some fast prototyping of grew requests, I can advise you to do request on a smaller part of the corpus by : 
- downloading the treebank you want
- downsampling it (take 1% for starting maybe)
- upload it in arboratorgrew (https://arboratorgrew.elizia.net/#/)
- create a project with your small treebank
- request your treebank

(also, the gew-match server of arborator grew is not down at the moment, so it will allow you to continue your work)

**Comment by LeonieWeissweiler** [comment]
Hi Kirian! We got so few matches on the subtypes of constructions that we're doing now, that I don't think this will work with a subsample of the treebank. I'm not too familiar with arboratorgrew, can I just find the German HDT treebank there somewhere or would I have to upload it myself?

**Comment by bguil** [comment]
You will not be able to upload all HDT in ArboratorGrew because it is too large.

@LeonieWeissweiler: regarding your request, I understand it with the trigram `X D F` but I don't see your point with `Y1` and `Y2`. 

Without the `Y1` and `Y2` line, the first occurrence is: _Für den Fall , dass der Staat dies nicht finanzieren könne , stellt er außerdem die Hilfe der Netzbetreiber in Aussicht :_

But with the two other lines:
 - `Y1` can be any other word except _dass_, so it can be _der_, _Staat_, … _Aussicht_ or _:_ (17 solutions)
 - for each `Y1`, `Y2` can be any other of the 16 words
That gives 272 (17*16) different solutions.

I suppose that it is not what you want to search for.

**Comment by LeonieWeissweiler** [comment]
yes, I then realised that I had forgotten the Y1<F; Y2<Y1; but when I tried that I was still getting errors. It works now, though! (returning no results, but also not throwing an error)

So the lesson for me is, don't run a query on HDT that could result in too many matches?

**Comment by kirianguiller** [comment]
> So the lesson for me is, don't run a query on HDT that could result in too many matches?

The problem is more that, because the Y1 and Y2 condition were incomplete, the query resulted in around N² results for each sentence (of N nodes) that were corresponding to the other conditions. It can be too much maybe ? (I don't know how works the grew research algorithm)

Here is the small subsample (952 sentences) for german HUD : https://arboratorgrew.elizia.net/?#/projects/UD_German_HDT_subsample
